name: CMake on a single platform

on:
  push:
    branches: [ "cmake2" ]
  pull_request:
    branches: [ "cmake2" ]

env:
  BUILD_TYPE: Release
  TARGET: FightClubGame

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -v --target ${{env.TARGET}}

    - name: Archive Build Directory
      run: zip -r ${{env.TARGET}}-${{env.BUILD_TYPE}}.zip ${{github.workspace}}/build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.TARGET}}-${{env.BUILD_TYPE}}
        path: ${{env.TARGET}}-${{env.BUILD_TYPE}}.zip
